name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test with RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install libpq-dev

      - name: Setup database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run RSpec tests
        run: bundle exec rspec

  lint:
    name: Lint with Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop
